name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - uses: TykTechnologies/actions/docker-login@main
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: TykTechnologies/actions/docker-build-push@main
        with:
          dockerfile: Dockerfile
          tags: ${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          repository_name: redis-cluster-operator
